### ISSUE TITLE
"That icon..." [Suggestion]

### ISSUE THREAD

**Issue by DeveloperWOW64** [Rise-Software/Rise-Notes#16]
**Is your feature request related to a problem? Please describe.**

The icon is very nice, but there's one thing that needs to be changed; the '**R**' in the logo looks very off and not fluent due to the fact that it is serif.

**Describe the solution you'd like**

The '**R**' should be removed.

**Describe alternatives that would make the app better**

Instead of being completely removed, the **R** could be replaced with a sans-serif alternative or an icon like:
![image](https://user-images.githubusercontent.com/71598437/190457023-270b40fe-515b-441c-be5d-12a237d16656.png)

**Comment by DeveloperWOW64** [comment]
![image](https://user-images.githubusercontent.com/71598437/190470109-e70d4257-032e-4801-b13f-d8a39bf29f97.png)

**Comment by HuyHung1408** [comment]
I'm not sure if they will continue to work on this though.
